Overall design improvements
gdsc-ipsacademy/Connect-Four-Game pull request #19
Opened 2023-10-20 13:23 UTC by itrajkov

- Color palette
- Menus design
- Board + Coins design
- Assets restructure
- Consistent name casing `snake_case`
- Various bugfixes

2023-10-20 13:25 UTC, itrajkov commented
This addresses a part of #8. I wanted to split the PR up in logical units in favor of not having a huge PR.
Next PR is going to address the specific requests in #8 .

2023-10-20 17:21 UTC, JustA3DObject commented on assets/img/bg.jpeh
The file extension has a typo. I think you meant to write .jpeg because I don't think .jpeh is a valid extension. (This asset is unused in the code btw)

2023-10-20 17:22 UTC, JustA3DObject requested changes
The UI looks fantastic but I'd like to point out a couple of things:
- The game does not render "Thinking" Label anymore while AI is calculating next move. This is important for 4th and 5th difficulty levels.
- Variables used for buttons in `game.py` could be written better. Button height and width for restart, quit and difficulty level buttons should have been declared in `variables.py` to keep the code consistent and keep all the variables easy to find and change by anyone. (This was implemented in the latest release)
- The thinking time should be applied for levels 1 to 3 instead of just level 1 because the AI takes almost no time to calculate next move in these levels. (This was implemented in the latest release)

2023-10-21 00:05 UTC, itrajkov commented
> The UI looks fantastic but I'd like to point out a couple of things:
> 
> * The game does not render "Thinking" Label anymore while AI is calculating next move. This is important for 4th and 5th difficulty levels.
> * Variables used for buttons in `game.py` could be written better. Button height and width for restart, quit and difficulty level buttons should have been declared in `variables.py` to keep the code consistent and keep all the variables easy to find and change by anyone. (This was implemented in the latest release)
> * The thinking time should be applied for levels 1 to 3 instead of just level 1 because the AI takes almost no time to calculate next move in these levels. (This was implemented in the latest release)

I fixed point 1 but point 2 and 3 were already applied in my PR.

2023-10-21 08:38 UTC, JustA3DObject approved these changes
LGTM

2023-10-21 08:38 UTC, merged